# Generated by Django 5.0.5 on 2024-05-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('mail', models.EmailField(max_length=50, null=True)),
                ('password', models.CharField(max_length=20)),
                ('talanet', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
