# Generated by Django 5.0.5 on 2024-05-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userform',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='userform',
            name='mail',
            field=models.EmailField(default='user@xxxxx.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='userform',
            name='name',
            field=models.CharField(default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='userform',
            name='talanet',
            field=models.CharField(choices=[('Company Admin', 'Company Admin'), ('Recuiter', 'Recuiter'), ('Job Seeker', 'Job Seeker'), ('Free Lancer', 'Free Lancer')], default='Company Admin', max_length=20),
        ),
    ]
