# Generated by Django 5.0.5 on 2024-05-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_adminform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminForm',
        ),
        migrations.AlterField(
            model_name='userform',
            name='mail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userform',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='talanet',
            field=models.CharField(max_length=20),
        ),
    ]
