# Generated by Django 5.0.5 on 2024-05-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_delete_adminform_alter_userform_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='mail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='talanet',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
