# Generated by Django 5.0.5 on 2024-05-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_userform_mail_alter_userform_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('mail', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('companyName', models.CharField(max_length=20, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
