# Generated by Django 5.0.5 on 2024-05-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_adminform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, null=True)),
                ('salary', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=20, null=True)),
                ('companyName', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
