# Generated by Django 5.0.5 on 2024-05-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='JobForm',
        ),
    ]
