# Generated by Django 5.0.5 on 2024-05-14 00:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_jobform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobform',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Closed', 'Closed')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
